service: aem

provider:
  name: google
  # Switch to nodejs8 after Serverless 2.0.0 has been published.
  # node 8 allows console.debug which is handy for logging payloads.
  runtime: nodejs
  project: convo-aem
  credentials: ~/dev/workspace-shine/adaptto-2019-demo/aem-voice-demo/convo-aem/conf/credentials.json # path needs to be absolute

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    # Comment out node_modules when you want to use a local convo-node.
    # - node_modules/**
    - .gitignore
    - .git/**

functions:
  dialogFlow:
    handler: dialogflow
    events:
      - http: blah
